//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IshbulatovGlaza1920
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media;

    public partial class Agent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.AgentPriorityHistory = new HashSet<AgentPriorityHistory>();
            this.ProductSale = new HashSet<ProductSale>();
            this.Shop = new HashSet<Shop>();
        }
    
        public int ID { get; set; }
        public int AgentTypeID { get; set; }
        public string Title { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Logo { get; set; }
        public string Address { get; set; }
        public int Priority { get; set; }
        public string DirectorName { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }

        public string LogoPath
        {
            get
            {
                if (string.IsNullOrEmpty(Logo)) return null;
                return Logo;
            }
        }

        public decimal Sales //сумма продаж высчитывается складывая стоимость каждой продажи
        {
            get
            {
                decimal s = 0;
                foreach (ProductSale p in ProductSale)
                {
                    s += p.Stoimost;
                }
                return s;
            }
        }

        public decimal Discount //используется для расчета процентов по скидке на основе суммы продаж
        {
            get
            {
                var ctx = IshbulatovGlazaEntities.GetContext();
                decimal total = ctx.ProductSale.Where(ps => ps.AgentID == ID && ps.SaleDate.Year == DateTime.Now.Year)
                    .AsEnumerable()
                    .Sum(ps => ps.ProductCount * (decimal.TryParse(ps.Product.MinCostForAgent, out decimal c) ? c : 0));

                if (total <= 10000) return 0;
                if (total <= 50000) return 5;
                if (total <= 150000) return 10;
                if (total <= 300000) return 15;
                return 20;
            }
        }

        public int SalesForYear
        {
            get
            {
                using (var context = new IshbulatovGlazaEntities())
                {
                    return context.ProductSale
                        .Where(ps => ps.AgentID == ID && ps.SaleDate.Year == DateTime.Now.Year) 
                        //.Where(ps => ps.AgentID == ID && ps.SaleDate.Year == 2019) //чтобы продажи за год показывались
                        .Sum(ps => (int?)ps.ProductCount) ?? 0;
                }
            }
        }

        public SolidColorBrush RowColor
        {
            get
            {
                return Discount >= 25 ? new SolidColorBrush(Colors.LightGreen) : new SolidColorBrush(Colors.Transparent);
            }
        }


        public virtual AgentType AgentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AgentPriorityHistory> AgentPriorityHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductSale> ProductSale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shop> Shop { get; set; }
    }
}
